Verifiers parsing
cchangelabs/ilcdlib pull request #10
Opened 2023-06-09 12:58 UTC by dsenchishen

2023-06-09 16:34 UTC, corvis commented
@dsenchishen linter failed

2023-06-09 18:34 UTC, corvis requested changes

2023-06-09 18:34 UTC, corvis commented on src/ilcdlib/dto.py
> +class OrgDto:
Why do we need an extra DTO for Org? Use `openepd.Org`

2023-06-09 18:34 UTC, corvis commented on src/ilcdlib/dto.py
> +    validation_type: str | None
add `org: Org`

2023-06-09 18:34 UTC, corvis commented on src/ilcdlib/dto.py
> +class ValidationDto(OrgDto):
Inheritance is very unnatural here. Validation IS NOT an Org

2023-06-09 18:34 UTC, corvis commented on src/ilcdlib/epd/reader.py
> +        epd.set_ext_field("epd_verifiers", self.get_verifiers(lang))
Rebase on dev as we put extensions under `ilcd` key now

2023-06-09 18:34 UTC, corvis commented on src/ilcdlib/epd/reader.py
>          )
Invoke `get_verifiers` and group verifications by 2 groups: `internal` and external. Internal should go under ext, the first item from external goes to `third_party_verifier`

2023-06-12 21:48 UTC, corvis requested changes

2023-06-12 21:48 UTC, corvis commented on src/ilcdlib/epd/reader.py
> +            third_party_verifier=self.get_third_party_verifier(lang),
This should be `Org` object, not your dto.

2023-06-12 21:48 UTC, corvis commented on src/ilcdlib/epd/reader.py
> +            epd_verifiers=self.get_verifiers(lang),
Let's move this under ILCD extensions

2023-06-13 15:57 UTC, corvis requested changes

2023-06-13 15:57 UTC, corvis commented on src/ilcdlib/extension.py
> +    epd_verifiers: list[Org] | None = None
in extension it should be DTO with type field. Otherwise there is no way to understand which one is of what type.

2023-06-14 14:07 UTC, corvis commented on src/ilcdlib/epd/reader.py
> +    def get_verifiers(self, lang: LangDef) -> list[ValidationDto]:
`_get_all_verifiers` is not needed any more. Move logic from `_get_all_verifiers` to this method

2023-06-14 15:47 UTC, dsenchishen commented
> @dsenchishen Squash and rebase pls

Sorry, I missed to squash commits

2023-06-15 12:31 UTC, merged